WebApplication1/WebApplication1/Controllers/AuthorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Models;
using WebApplication1.Models.Interfaces;

namespace WebApplication1.Controllers
{
    public class AuthorsController : Controller
    {
        private readonly MyDbContext _context;
        private readonly IAuthorRepository authorRepository;

        public AuthorsController(MyDbContext context , IAuthorRepository authorRepository)
        {
            _context = context;
            this.authorRepository = authorRepository;
        }

        // GET: Authors
        public async Task<IActionResult> Index()
        {
            var val = authorRepository.GetAll();
            

            return View(val);
        }

        

        // GET: Authors/Create
        public IActionResult Create()
        {
            return View();
        }
         
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(  Author author)
        {
            if (ModelState.IsValid)
            {
                authorRepository.Create(author);
                return RedirectToAction(nameof(Index));
            }
            return View(author);
        }

        // GET: Authors/Edit/5
        public async Task<IActionResult> Edit(int id)
        {

            var author = authorRepository.GetById(id);
            if (author == null)
            {
                return NotFound();
            }
            return View(author);
        }
 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit( Author author)
        {

            if (ModelState.IsValid)
            {
                try
                {
                    authorRepository.Update(author);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AuthorExists(author.AuthorId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(author);
        }

        // GET: Authors/Delete/5
        public async Task<IActionResult> Delete(int id)
        {


            var author = authorRepository.GetById(id);
            if (author == null)
            {
                return NotFound();
            }
            authorRepository.Delete(author);
            return RedirectToAction(nameof(Index));
        }

        

        private bool AuthorExists(int id)
        {
            return _context.Authors.Any(e => e.AuthorId == id);
        }
    }
}

WebApplication1/WebApplication1/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Models;
using WebApplication1.Models.Interfaces;

namespace WebApplication1.Controllers
{
    public class BooksController : Controller
    {
        private readonly MyDbContext _context;
        private readonly IBookRepository bookRepository;
        private readonly IAuthorRepository authorRepository;

        public BooksController(MyDbContext context , IBookRepository bookRepository , IAuthorRepository authorRepository)
        {
            _context = context;
            this.bookRepository = bookRepository;
            this.authorRepository = authorRepository;
        }

        // GET: Books
        public async Task<IActionResult> Index(int ? authorId , int  ? BorrowId)
        {
            if(authorId != null)
            {
                var books = authorRepository.GetWithBooks((int)authorId);
                return View(books);
            }
            if(BorrowId != null)
            {
                var books = bookRepository.FindWithAuthorAndBorrower(x=>x.BorrowerId==BorrowId);
                return View(books);
            }
            else
            {
                var books = bookRepository.GetAllWithAuthor();
                return View(books);

            }
           // var myDbContext = _context.Books.Include(b => b.Author).Include(b => b.Borrower);
            //return View(await myDbContext.ToListAsync());
        }
 
        // GET: Books/Create
        public IActionResult Create()
        {
            ViewData["AuthorId"] = new SelectList(authorRepository.GetAll(), "AuthorId", "Name");
            //ViewData["BorrowerId"] = new SelectList(_context.Customers, "CustomerId", "Name");
            return View();
        }
 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create( Book book)
        {
            if (ModelState.IsValid)
            {
                //_context.Add(book);
                //await _context.SaveChangesAsync();
                 
                bookRepository.Create(book);
                return RedirectToAction(nameof(Index));
            }
            ViewData["AuthorId"] = new SelectList(authorRepository.GetAll(), "AuthorId", "Name", book.AuthorId);
            //ViewData["BorrowerId"] = new SelectList(_context.Customers, "CustomerId", "Name", book.BorrowerId);
            return View(book);
        }

        // GET: Books/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = bookRepository.GetById((int)id);
            if (book == null)
            {
                return NotFound();
            }
            ViewData["AuthorId"] = new SelectList(authorRepository.GetAll(), "AuthorId", "Name", book.AuthorId);
            //ViewData["BorrowerId"] = new SelectList(_context.Customers, "CustomerId", "Name", book.BorrowerId);
            return View(book);
        }

         
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Book book)
        {
          
            if (ModelState.IsValid)
            {
                try
                {
                    bookRepository.Update(book);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BookExists(book.BookId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AuthorId"] = new SelectList(authorRepository.GetAll(), "AuthorId", "Name", book.AuthorId);
            //ViewData["BorrowerId"] = new SelectList(_context.Customers, "CustomerId", "Name", book.BorrowerId);
            return View(book);
        }

        // GET: Books/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = bookRepository.GetById((int) id);
            if (book == null)
            {
                return NotFound();
            }
            bookRepository.Delete(book);
            return RedirectToAction(nameof(Index));
        }
 

        private bool BookExists(int id)
        {
            return _context.Books.Any(e => e.BookId == id);
        }
    }
}

WebApplication1/WebApplication1/Controllers/LendController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Models;
using WebApplication1.Models.Interfaces;

namespace WebApplication1.Controllers
{
    public class LendController : Controller
    {
        private readonly IBookRepository bookRepository;
        private readonly ICustomerRepository customerRepository;

        public LendController(IBookRepository bookRepository , ICustomerRepository customerRepository)
        {
            this.bookRepository = bookRepository;
            this.customerRepository = customerRepository;
        }

        public IActionResult Index()
        {
            // avaliable book
            //var avaliable= bookRepository.FindWithAuthor(x=>x.BorrowerId == null);
            var avaliable= bookRepository.FindWithAuthor(x=>x.Borrower == null);
            if (avaliable == null) { return RedirectToAction("Index", "Home"); }


            return View(avaliable);
        }

        public IActionResult LendBook(int bookId)
        {

            var val = bookRepository.GetById(bookId);
            ViewData["BorrowerId"] = new SelectList(customerRepository.GetAll(), "CustomerId", "Name");

            return View(val);
        }


        [HttpPost]
        public IActionResult LendBook(Book book)
        {
            if (ModelState.IsValid)
            {
                //var book2 = bookRepository.GetById(book.BookId);
                //var customer = customerRepository.GetById((int) book.BorrowerId);
                //book.Borrower = customer;
               // bookRepository.Update(book2);

                bookRepository.Update(book);
                return RedirectToAction("Index");
            }
            ViewData["BorrowerId"] = new SelectList(customerRepository.GetAll(), "CustomerId", "Name",book.BorrowerId);
            return View(book);
        }


    }
}

WebApplication1/WebApplication1/Controllers/ReturnController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Models;
using WebApplication1.Models.Interfaces;

namespace WebApplication1.Controllers
{
    public class ReturnController : Controller
    {


        private readonly IBookRepository bookRepository;
        private readonly ICustomerRepository customerRepository;

        public ReturnController(IBookRepository bookRepository, ICustomerRepository customerRepository)
        {
            this.bookRepository = bookRepository;
            this.customerRepository = customerRepository;
        }
        public IActionResult Index()
        {
            // Returned books
             var returnBook = bookRepository.FindWithAuthorAndBorrower(x => x.BorrowerId != null);
            // var returnBook = bookRepository.FindWithAuthorAndBorrower(x => x.Borrower != null);
            if (returnBook == null) { return RedirectToAction("Index", "Home"); }


            return View(returnBook);
        }

         
        public IActionResult ReturnBook(int bookid)
        {
            if (ModelState.IsValid)
            {
                var book = bookRepository.GetById(bookid);
                book.Borrower = null;
                book.BorrowerId = null;
                bookRepository.Update(book);
            }
            return RedirectToAction("Index");
        }

    }
}

WebApplication1/WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplication1</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                       
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customers" asp-action="Index"> Customers </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Authors" asp-action="Index"> Authors </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Books" asp-action="Index"> Books </a>
                        </li>
                            <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Lend" asp-action="Index"> Lend </a>
                        </li>


                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Return" asp-action="Index"> Return </a>
                        </li>
                        
                    

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - WebApplication1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>